#!/usr/bin/env python3
"""
Simple Filesystem Watcher for Digital FTE - Bronze Tier Demo
Monitors a directory for new files and creates tasks in the vault.
"""

import os
import sys
import time
from pathlib import Path
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

VAULT_PATH = Path.home() / "AI_Employee_Vault"
WATCH_PATH = Path.home() / "AI_Employee_Vault" / "Inbox"
INBOX_PATH = VAULT_PATH / "Inbox"


class VaultFileHandler(FileSystemEventHandler):
    """Handle filesystem events and create tasks"""

    def on_created(self, event):
        if event.is_directory:
            return

        file_path = Path(event.src_path)

        # Skip if it's already a markdown file (task)
        if file_path.suffix == '.md':
            return

        # Skip hidden files and temp files
        if file_path.name.startswith('.') or file_path.name.endswith('~'):
            return

        print(f"[{datetime.now().isoformat()}] New file detected: {file_path.name}")

        # Create a task for the new file
        task_name = f"process-{file_path.stem}"
        task_file = INBOX_PATH / f"{task_name}.md"

        # Avoid duplicates
        if task_file.exists():
            task_file = INBOX_PATH / f"{task_name}-{int(time.time())}.md"

        task_content = f"""# Process File: {file_path.name}

**Priority**: Normal
**Created**: {datetime.now().isoformat()}
**Status**: New
**File**: {file_path.absolute()}

## Description
A new file was detected in the monitored directory and needs processing.

## Requirements
- [ ] Review file contents
- [ ] Determine action needed
- [ ] Process or archive

## File Info
- Name: {file_path.name}
- Size: {file_path.stat().st_size} bytes
- Type: {file_path.suffix or 'no extension'}

## Notes
Auto-generated by Filesystem Watcher.
"""

        try:
            task_file.write_text(task_content)
            print(f"✓ Created task: {task_file.name}")
        except Exception as e:
            print(f"✗ Error creating task: {e}")


def main():
    """Start the filesystem watcher"""

    # Ensure vault exists
    if not VAULT_PATH.exists():
        print(f"Error: Vault not found at {VAULT_PATH}")
        print("Run 'fte vault init' first")
        sys.exit(1)

    # Ensure Inbox exists
    INBOX_PATH.mkdir(exist_ok=True)

    # Create a test watch directory if it doesn't exist
    watch_dir = Path.home() / "AI_Employee_Vault" / "Watch"
    watch_dir.mkdir(exist_ok=True)

    print("=" * 60)
    print("Digital FTE - Filesystem Watcher (Bronze Tier)")
    print("=" * 60)
    print(f"Vault: {VAULT_PATH}")
    print(f"Watching: {watch_dir}")
    print(f"Tasks created in: {INBOX_PATH}")
    print("")
    print("Monitoring for new files...")
    print("Press Ctrl+C to stop")
    print("=" * 60)

    # Create observer and handler
    event_handler = VaultFileHandler()
    observer = Observer()
    observer.schedule(event_handler, str(watch_dir), recursive=False)

    # Start watching
    observer.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n\nStopping watcher...")
        observer.stop()

    observer.join()
    print("Watcher stopped.")


if __name__ == "__main__":
    main()
